dist: trusty

matrix:
  fast_finish: true

sudo: false

language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - nightly

cache:
  pip: true

# command to install dependencies
install:
  - pip install codecov
  - pip install pipenv

before_script:
  - export CI=True
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pipenv install --dev

# command to run tests
script: coverage run tests/runtests.py

after_success:
  - codecov
